name: Update Stats Cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Dark Theme Top Languages Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=LaWeite&theme=dark&hide_border=true&count_private=true&exclude_repo=github-readme-stats,anuraghazra.github.io,Basics_of_statistics
          path: stats/top-langs-dark.svg
          token: ${{ secrets.PAT_TOKEN }}

      - name: Generate Light Theme Top Languages Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=LaWeite&hide_border=true&count_private=true&exclude_repo=github-readme-stats,anuraghazra.github.io,Basics_of_statistics
          path: stats/top-langs-light.svg
          token: ${{ secrets.PAT_TOKEN }}

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add stats/*.svg
          git commit -m "Update stats cards" || echo "No changes to commit"
          git pull --rebase origin main
          git push
